flowchart LR
    %%
    %% nextflow.cli.CmdRun
    %%
    run --> checkRunName
    checkRunName --> matchRunName

    run --> getScriptFile
    getScriptFile --> getScriptFile0
    getScriptFile0 --> tryReadFromStdin
    tryReadFromStdin --> getScriptFromStream

    run --> launchInfo
    launchInfo --> detectDslMode

    run --> checkConfigEnv

    hasParams --> getParamsFile

    parsedParams --> getParamsFile

    parsedParams --> validateParamsFile

    parsedParams --> readJsonFile
    readJsonFile --> replaceVars0

    parsedParams --> readYamlFile
    readYamlFile --> replaceVars0

    parsedParams --> addParam
    addParam --> parseParamValue
