flowchart LR
    %%
    %% nextflow.Session
    %%
    create

    init

    fireDataflowNetwork --> checkConfig
    fireDataflowNetwork --> notifyFlowBegin
    fireDataflowNetwork --> callIgniters

    checkConfig --> validateConfig
    validateConfig --> validateConfig0
    validateConfig0 --> checkValidProcessName

    start --> registerSignalHandlers
    start --> notifyFlowCreate

    await --> joinAllOperators

    destroy --> shutdown0
    shutdown0 --> notifyFlowComplete

    fault --> cancel
    fault --> abort

    cancel --> notifyError

    abort --> dumpNetworkStatus
    abort --> notifyError
    abort --> operatorsForceTermination
