classDiagram
    %%
    %% nextflow.config
    %%
    CmdRun --> ConfigMap : run
    Session --* ConfigMap

    ConfigBuilder --> ConfigParser : build
    ConfigBuilder --> ConfigMap : build
    ConfigParser --> ConfigBase : parse
