classDiagram
    %%
    %% nextflow.cache
    %%
    Session --* CacheDB
    %% CacheFactory --> CacheDB : createInstance

    CacheDB --* CacheStore

    CacheStore <|-- DefaultCacheStore

    class DefaultCacheStore {
        db : DB
        uniqueId : UUID
        runName : String
        baseDir : Path
        dataDir : Path
        indexFile : Path
    }
