#!/bin/bash
# NEXTFLOW TASK: merge (2)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/10/9188f1687fff3970c69e4f4c88f165/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/10/9188f1687fff3970c69e4f4c88f165/.command.begin
# task environment
export PATH="/Users/olafurh/git/nextflow/nextflow-private/tests/bin:$PATH"

[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f bam1
rm -f bam2
rm -f bam3
rm -f bai1
rm -f bai2
rm -f bai3
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/5f/8db58bd21c7ef66f9d786225f46b08/bam bam1
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/0f/86a16a28b0fc00de9061c9d3293354/bam bam2
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/f1/e5d5d537dd57694f81d4e1de264e16/bam bam3
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/5f/8db58bd21c7ef66f9d786225f46b08/bai bai1
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/0f/86a16a28b0fc00de9061c9d3293354/bai bai2
ln -s /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/f1/e5d5d537dd57694f81d4e1de264e16/bai bai3

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash -ue /Users/olafurh/git/nextflow/nextflow-private/tests/checks/scratch/10/9188f1687fff3970c69e4f4c88f165/.command.sh
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
