plugins = []
headers = []

[build]
edge_functions = "/Users/chris.hakkaart/workspace/architecture/nextflow/docs/netlify/edge-functions"
publish = "/Users/chris.hakkaart/workspace/architecture/nextflow/docs/build"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/chris.hakkaart/workspace/architecture/nextflow/docs"
command = "npm run build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
NODE_VERSION = "22"
NODE_OPTIONS = "--max-old-space-size=2048"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/*"
function = "robots-tag"

[functions]

[functions."*"]

[[redirects]]
from = "/nextflow/developer/index"
to = "/nextflow/developer"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/updating-syntax"
to = "/nextflow/strict-syntax"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/updating-spot-retries"
to = "/nextflow/guides/updating-spot-retries"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/metrics"
to = "/nextflow/tutorials/metrics"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/data-lineage"
to = "/nextflow/tutorials/data-lineage"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/workflow-outputs"
to = "/nextflow/tutorials/workflow-outputs"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/flux"
to = "/nextflow/tutorials/flux"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/developer/plugins"
to = "/nextflow/plugins/developing-plugins"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/plugins"
to = "/nextflow/plugins/plugins"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/channel"
to = "/nextflow/workflow"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/module/"
to = "/nextflow/modules/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nextflow/operator"
to = "/nextflow/reference/operator"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]