/*
 * Copyright 2024-2025, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nextflow.trace.config

import groovy.transform.CompileStatic
import nextflow.config.schema.ConfigOption
import nextflow.config.schema.ConfigScope
import nextflow.config.schema.ScopeName
import nextflow.script.dsl.Description
import nextflow.trace.TraceHelper

@ScopeName("trace")
@Description("""
    The `trace` scope controls the layout of the execution trace file generated by Nextflow.

    [Read more](https://nextflow.io/docs/latest/reference/config.html#trace)
""")
@CompileStatic
class TraceConfig implements ConfigScope {

    static final String DEF_FILE_NAME = "trace-${TraceHelper.launchTimestampFmt()}.txt"

    @ConfigOption
    @Description("""
        When `true`, enables the creation of the execution trace report file (default: `false`).
    """)
    final boolean enabled

    @ConfigOption
    @Description("""
        Comma-separated list of fields to be included in the report.

        [Read more](https://nextflow.io/docs/latest/tracing.html#trace-report)
    """)
    final String fields

    @ConfigOption
    @Description("""
        Trace file name (default: `'trace-<timestamp>.txt'`).
    """)
    final String file

    @ConfigOption
    @Description("""
        When `true`, overwrites any existing trace file with the same name.
    """)
    final boolean overwrite

    @ConfigOption
    @Description("""
        When `true`, uses raw number formatting i.e. durations are reported in milliseconds and memory in bytes.
    """)
    final boolean raw

    @ConfigOption
    @Description("""
        Character used to separate values in each row (default: `\t`).
    """)
    final String sep

    /* required by extension point -- do not remove */
    TraceConfig() {}

    TraceConfig(Map opts) {
        enabled = opts.enabled as boolean
        fields = opts.fields ?: ''
        file = opts.file ?: DEF_FILE_NAME
        overwrite = opts.overwrite as boolean
        raw = opts.raw as boolean
        sep = opts.sep ?: '\t'
    }

}
