/*
 * Copyright 2013-2025, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.data.cid.model

import groovy.transform.Canonical
import groovy.transform.CompileStatic
import nextflow.data.cid.serde.CidSerializable

import java.time.Instant

/**
 * Model a base class for workflow and task outputs
 *
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
@Canonical
@CompileStatic
class DataOutput implements CidSerializable {
    /**
     * Real path of the output data.
     */
    String path
    /**
     * Checksum of the output data.
     */
    Checksum checksum
    /**
     * Entity that generated the data. Possible entities are:
     * - a DataOutput if the workflow published from a task data.
     * - a TaskRun if the data is a task output.
     * - a WorkflowRun if the data is generated by the workflow (e.g., an index file).
     */
    String source
    /**
     * Reference to the WorkflowRun that generated the data.
     */
    String workflowRun
    /**
     * Reference to the task that generated the data.
     */
    String taskRun
    /**
     * Size of the data.
     */
    long size
    /**
     * Data creation date.
     */
    Instant createdAt
    /**
     * Data last modified date.
     */
    Instant modifiedAt
    /**
     * Annotations attached to the data
     */
    Map annotations
}
