/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.module

import org.yaml.snakeyaml.Yaml
import spock.lang.Specification
import spock.lang.TempDir

import java.nio.file.Path

/**
 * Tests for ModuleSpec
 *
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
class ModuleSpecTest extends Specification {

    @TempDir
    Path tempDir

    // =========================================================================
    // Render tests
    // =========================================================================

    def 'should validate complete spec' () {
        given:
        def spec = new ModuleSpec(
            name: 'nf-core/fastqc',
            version: '1.0.0',
            description: 'FastQC quality control',
            license: 'MIT'
        )

        when:
        def errors = spec.validate()

        then:
        errors.isEmpty()
        spec.isValid()
    }

    // =========================================================================
    // Render tests
    // =========================================================================

    def 'should render YAML with comment header'() {
        given:
        def spec = new ModuleSpec(name: 'my-namespace/fastqc')

        when:
        def yaml = spec.toYaml()

        then:
        yaml.startsWith('# This file was auto-generated by `nextflow module spec`.')
    }

    def 'should omit null fields and include present fields in rendered YAML'() {
        given:
        def spec = new ModuleSpec(
            name: 'nf-core/fastqc',
            version: '1.0.0',
            description: 'Run FastQC',
            license: 'MIT'
        )

        when:
        def parsed = new Yaml().load(spec.toYaml()) as Map

        then:
        parsed['name'] == 'nf-core/fastqc'
        parsed['version'] == '1.0.0'
        parsed['description'] == 'Run FastQC'
        parsed['license'] == 'MIT'
    }

    def 'should omit input and output sections when empty'() {
        given:
        def spec = new ModuleSpec(name: 'my-namespace/simple')

        when:
        def yaml = spec.toYaml()

        then:
        !yaml.contains('input:')
        !yaml.contains('output:')
        !yaml.contains('topics:')
    }

    def 'should include passthrough fields when present'() {
        given:
        def spec = new ModuleSpec(
            name: 'nf-core/fastqc',
            version: '1.0.0',
            _passthrough: [foo: 'bar']
        )

        when:
        def parsed = new Yaml().load(spec.toYaml()) as Map

        then:
        parsed['name'] == 'nf-core/fastqc'
        parsed['version'] == '1.0.0'
        parsed['foo'] == 'bar'
    }

}
