/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.executor.local

import java.nio.file.FileSystems
import java.nio.file.Files
import java.nio.file.Path

import groovy.transform.CompileStatic
import groovy.transform.PackageScope
import groovy.util.logging.Slf4j
import nextflow.executor.Executor
import nextflow.extension.FilesEx
import nextflow.processor.TaskRun

/**
 * Native task handler for an in-JVM agent, which MATERIALIZES the task's declared input files
 * into its work directory before the body runs.
 *
 * A typed `Path` input means the same thing for an agent as for a process: the value the agent
 * sees is a work-dir-relative name. For a canonical (containerized) agent the stage-in script
 * generated by {@code BashWrapperBuilder} makes that true; an in-JVM agent runs no wrapper and no
 * shell at all, so the file has to be linked in here or the name would resolve to nothing.
 *
 * Confined to the agent executor on purpose: native `exec` processes have the identical hole, but
 * fixing them means changing every native task and is a separate change.
 */
@Slf4j
@CompileStatic
class AgentTaskHandler extends NativeTaskHandler {

    protected AgentTaskHandler(TaskRun task, Executor executor) {
        super(task, executor)
    }

    @Override
    void submit() {
        materializeInputs(task)
        super.submit()
    }

    /**
     * Link (or copy) each declared input file into the task work directory under its stage name.
     * The work dir is created by {@code TaskProcessor} before the task is submitted, so it exists.
     *
     * Honours {@code stageInMode} with the same four strategies a scriptlet task gets from
     * {@link nextflow.executor.SimpleFileCopyStrategy}, since an agent resolves the full task
     * directive ladder from the `agent` config scope and a user may well set it there — including
     * the same hard failure on an unrecognized one, so a typo means the same thing in both.
     */
    @PackageScope
    static void materializeInputs(TaskRun task) {
        final inputs = task.getInputFilesMap()
        if( !inputs )
            return
        final workDir = task.workDir
        // Linking is a local-filesystem operation: a remote provider (S3, Azure, ...) throws
        // UnsupportedOperationException out of createSymbolicLink/createLink, which would escape
        // submit() and fail every agent task that declares a Path input. An agent whose work dir
        // is not local cannot use the staged names anyway -- its `fs:` tools refuse a non-file
        // scheme (ModuleToolBridge) -- so skip rather than turn a degraded case into a hard error.
        if( workDir.getFileSystem() != FileSystems.getDefault() ) {
            log.warn1 "Agent input files are not staged when the work directory is not a local path -- offending work dir: ${workDir}"
            return
        }
        final mode = task.config?.getStageInMode()
        for( final entry : inputs.entrySet() ) {
            final target = workDir.resolve(entry.key)
            // a stage name may carry a sub-directory (e.g. `dir/file.txt`)
            if( target.parent != null )
                Files.createDirectories(target.parent)
            Files.deleteIfExists(target)
            stageInput(entry.value, target, mode)
        }
    }

    private static void stageInput(Path source, Path target, String mode) {
        switch( mode ) {
            case 'copy':
                // via FilesEx so a directory input is copied recursively, as `cp -fRL` would
                FilesEx.copyTo(source, target)
                break
            case 'link':
                Files.createLink(target, source)
                break
            case 'rellink':
                Files.createSymbolicLink(target, relativize(source, target))
                break
            case null:
            case 'symlink':
                Files.createSymbolicLink(target, source.toAbsolutePath())
                break
            default:
                // same rejection SimpleFileCopyStrategy.stageInCommand makes, so a typo'd
                // `stageInMode` fails an agent exactly as loudly as it fails a process
                throw new IllegalArgumentException("Unknown stage-in strategy: $mode")
        }
    }

    /**
     * The link target for `rellink`. Both ends are canonicalized first, because relativizing a
     * path that traverses a symlinked ancestor (on macOS `/var` -> `/private/var`) yields a `..`
     * chain the kernel resolves physically, i.e. a dangling link. Degrades to the absolute path
     * when the two ends are not comparable — a relative link is an optimization, never a contract.
     */
    private static Path relativize(Path source, Path target) {
        final abs = source.toAbsolutePath()
        if( source.fileSystem != target.fileSystem )
            return abs
        try {
            return target.parent.toRealPath().relativize(abs.toRealPath())
        }
        catch( IOException e ) {
            log.debug "Unable to build a relative stage-in link for `${source}` - ${e.message}"
            return abs
        }
    }

}
