classDiagram
    %%
    %% nextflow.secret
    %%
    CmdRun --> SecretsProvider : run

    SecretsLoader --> SecretsProvider : load
    SecretsProvider --> Secret : getSecret
    SecretsProvider <|-- LocalSecretsProvider
    Secret <|-- SecretImpl
