classDiagram
    %%
    %% nextflow.secret
    %%
    ConfigBuilder --> SecretsLoader : build
    BaseScript --> SecretsLoader : run
    BashWrapperBuilder --> SecretsLoader : build

    SecretsLoader --> SecretsProvider : load
    SecretsProvider --> Secret : getSecret
    SecretsProvider <|-- LocalSecretsProvider
    Secret <|-- SecretImpl
