/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nextflow.script

import groovy.transform.CompileStatic
import groovy.transform.PackageScope
import groovy.util.logging.Slf4j
import nextflow.script.params.v2.ProcessFileInput
import nextflow.script.params.v2.ProcessFileOutput

/**
 * Runtime delegate that captures an agent body when the lowered agent closure
 * runs. Directives are captured via {@link #methodMissing} against a known set;
 * inputs/outputs via {@code _input_}/{@code _output_}; the implicit file
 * stagers/unstagers the compiler infers from the declared types via
 * {@code stageAs}/{@code _unstage_files}; the prompt via {@link #withPrompt}.
 * {@link #build} produces the populated {@link AgentDef}.
 *
 * The staging methods record the SAME value types {@code ProcessDslV2} records,
 * because an agent's typed I/O is a process's typed I/O.
 *
 * Distinct from {@code nextflow.script.dsl.AgentDsl} (the compile-time
 * resolution scope).
 */
@Slf4j
@CompileStatic
class AgentBuilder {

    static final List<String> DIRECTIVES = ['model', 'instruction', 'goal', 'tools', 'skills', 'maxIterations', 'label']

    private BaseScript ownerScript
    private String agentName

    private final Map<String,Object> directives = new LinkedHashMap<>()
    private final List<AgentInput> inputs = new ArrayList<>()
    private final List<AgentOutput> outputs = new ArrayList<>()
    private final List<ProcessFileInput> fileInputs = new ArrayList<>()
    private final Map<String,ProcessFileOutput> fileOutputs = new LinkedHashMap<>()
    private PromptDef prompt

    AgentBuilder(BaseScript ownerScript, String agentName) {
        this.ownerScript = ownerScript
        this.agentName = agentName
    }

    protected void checkName(String name) {
        if( !DIRECTIVES.contains(name) )
            throw new IllegalArgumentException("Unknown agent directive `${name}`")
    }

    // NOTE: replace with internal DSL -- as done for inputs/outputs and config options
    // -- once the v1 parser is removed. The agent primitive is only supported by the v2
    // parser, so this dynamic dispatch is provisional and carries no v1 requirement.
    @PackageScope
    Object methodMissing(String name, Object args) {
        checkName(name)
        final values = args instanceof Object[] ? (args as List) : [args]
        // `label` is repeatable, exactly as for a process: accumulate instead of overwriting
        if( name == 'label' ) {
            final labels = (List) directives.computeIfAbsent('label', { k -> new ArrayList() })
            labels.addAll(values)
        }
        else
            directives.put(name, values.size() == 1 ? values[0] : values)
        return null
    }

    void _input_(String name, Class type, boolean optional = false) {
        inputs.add(new AgentInput(name, type, optional))
    }

    /** A null `value` is a bare output the model answers; an explicit RHS is the value itself. */
    void _output_(String name, Class type, Closure value = null) {
        outputs.add(new AgentOutput(name, type, value))
    }

    /**
     * Declare a file (or collection of files) to be staged into the task directory.
     * Generated by the compiler for every Path-typed input, exactly as for a process.
     */
    void stageAs(Object value) {
        fileInputs.add(new ProcessFileInput(null, value))
    }

    void stageAs(Object value, Object filePattern) {
        fileInputs.add(new ProcessFileInput(filePattern, value))
    }

    /**
     * Declare a file (or collection of files) to be unstaged from the task directory.
     * Generated by the compiler for a `file(...)`/`files(...)` call in an output expression.
     */
    void _unstage_files(String key, Object pattern) {
        fileOutputs.put(key, new ProcessFileOutput(pattern))
    }

    AgentBuilder withPrompt(PromptDef prompt) {
        this.prompt = prompt
        return this
    }

    AgentDef build() {
        if( prompt == null )
            throw new IllegalStateException("Missing prompt in agent `${agentName}` definition")
        return new AgentDef(ownerScript, agentName, directives, inputs, outputs, prompt, fileInputs, fileOutputs)
    }

    @CompileStatic
    static class AgentInput {
        final String name
        final Class type
        /** Declared with a trailing `?`; a null value is then admitted and stages nothing. */
        final boolean optional
        AgentInput(String name, Class type, boolean optional = false) {
            this.name = name; this.type = type; this.optional = optional
        }
    }

    @CompileStatic
    static class AgentOutput {
        final String name
        final Class type
        /**
         * The declared right-hand side, or null for a bare output. A non-null value takes the
         * output OUT of the model-answered set: its value is the expression, exactly as for a
         * process output.
         */
        final Closure value
        AgentOutput(String name, Class type, Closure value = null) {
            this.name = name; this.type = type; this.value = value
        }
    }
}
