flowchart LR
    %%
    %% nextflow.ast.NextflowDSLImpl
    %%
    visit --> visitMethod
    visit --> visitObjectInitializerStatements
    visit --> visitMethodCallExpression
    visit --> visitExpressionStatement

    visitMethod --> isIllegalName

    visitObjectInitializerStatements --> injectMetadata
    injectMetadata --> makeSetProcessNamesStm

    visitMethodCallExpression --> convertProcessDef
    visitMethodCallExpression --> convertWorkflowDef

    visitExpressionStatement --> convertIncludeDef

    convertProcessDef --> isIllegalName
    convertProcessDef --> convertProcessBlock

    convertProcessBlock --> fixLazyGString
    convertProcessBlock --> fixStdinStdout
    convertProcessBlock --> fixDirectiveWithNegativeValue
    convertProcessBlock --> convertInputMethod
    convertProcessBlock --> convertOutputMethod
    convertProcessBlock --> readSource
    convertProcessBlock --> addWhenGuardCall
    convertProcessBlock --> addStubCall
    convertProcessBlock --> makeScriptWrapper
    convertProcessBlock --> wrapExpressionWithClosure

    convertInputMethod --> fixMethodCall
    convertInputMethod --> isWithinMethod
    convertInputMethod --> varToConstX
    convertOutputMethod --> fixMethodCall
    convertOutputMethod --> fixOutEmitOption
    addWhenGuardCall --> createBlock0
    addStubCall --> createBlock0
    makeScriptWrapper --> fetchVariables
    wrapExpressionWithClosure --> makeScriptWrapper

    fixMethodCall --> isOutputWithPropertyExpression
    fixMethodCall --> wrapPropertyToClosure
    fixMethodCall --> varToConstX

    varToConstX --> vartoStrX

    vartoStrX --> wrapPropertyToClosure

    convertWorkflowDef --> makeWorkflowDefWrapper
    convertWorkflowDef --> isIllegalName

    makeWorkflowDefWrapper --> normWorkflowParam
    makeWorkflowDefWrapper --> readSource
    makeWorkflowDefWrapper --> makeScriptWrapper

    normWorkflowParam --> createAssignX
    createAssignX --> hasTo
    createAssignX --> getNextName
