flowchart LR
    %%
    %% nextflow.config.ConfigBuiler
    %%
    build --> buildConfigObject
    build --> toConfigMap

    buildConfigObject --> validateConfigFiles
    buildConfigObject --> buildGivenFiles
    buildConfigObject --> configRunOptions

    buildGivenFiles --> wrapValue
    buildGivenFiles --> buildConfig0
    buildConfig0 --> merge0
    buildConfig0 --> checkValidProfile
    merge0 --> parse0
    merge0 --> validate

    configRunOptions --> normalizeResumeId
    configRunOptions --> mergeMaps
    configRunOptions --> configContainer
    mergeMaps --> getConfigVal0
    configContainer --> hasContainerDirective

    toConfigMap --> normalize0
