/*
 * workflow_execution.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nextflow.ga4gh.wes.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Ga4ghWesWorkflowListRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-01T15:34:23.960Z")
public class Ga4ghWesWorkflowListRequest {
  @SerializedName("page_size")
  private Long pageSize = null;

  @SerializedName("page_token")
  private String pageToken = null;

  @SerializedName("key_value_search")
  private String keyValueSearch = null;

  public Ga4ghWesWorkflowListRequest pageSize(Long pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * OPTIONAL Number of workflows to return at once. Defaults to 256, and max is 2048.
   * @return pageSize
  **/
  @ApiModelProperty(value = "OPTIONAL Number of workflows to return at once. Defaults to 256, and max is 2048.")
  public Long getPageSize() {
    return pageSize;
  }

  public void setPageSize(Long pageSize) {
    this.pageSize = pageSize;
  }

  public Ga4ghWesWorkflowListRequest pageToken(String pageToken) {
    this.pageToken = pageToken;
    return this;
  }

   /**
   * OPTIONAL Token to use to indicate where to start getting results. If unspecified, returns the first page of results.
   * @return pageToken
  **/
  @ApiModelProperty(value = "OPTIONAL Token to use to indicate where to start getting results. If unspecified, returns the first page of results.")
  public String getPageToken() {
    return pageToken;
  }

  public void setPageToken(String pageToken) {
    this.pageToken = pageToken;
  }

  public Ga4ghWesWorkflowListRequest keyValueSearch(String keyValueSearch) {
    this.keyValueSearch = keyValueSearch;
    return this;
  }

   /**
   * Get keyValueSearch
   * @return keyValueSearch
  **/
  @ApiModelProperty(value = "")
  public String getKeyValueSearch() {
    return keyValueSearch;
  }

  public void setKeyValueSearch(String keyValueSearch) {
    this.keyValueSearch = keyValueSearch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ga4ghWesWorkflowListRequest ga4ghWesWorkflowListRequest = (Ga4ghWesWorkflowListRequest) o;
    return Objects.equals(this.pageSize, ga4ghWesWorkflowListRequest.pageSize) &&
        Objects.equals(this.pageToken, ga4ghWesWorkflowListRequest.pageToken) &&
        Objects.equals(this.keyValueSearch, ga4ghWesWorkflowListRequest.keyValueSearch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageSize, pageToken, keyValueSearch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ga4ghWesWorkflowListRequest {\n");
    
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageToken: ").append(toIndentedString(pageToken)).append("\n");
    sb.append("    keyValueSearch: ").append(toIndentedString(keyValueSearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

