/*
 * workflow_execution.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nextflow.ga4gh.wes.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * ReturnEnvelopeForWorkflowListing
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-01T15:34:23.960Z")
public class ReturnEnvelopeForWorkflowListing {
  @SerializedName("workflows")
  private List<SmallDescriptionOfWorkflowsReturnedByServerDuringListing> workflows = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;

  public ReturnEnvelopeForWorkflowListing workflows(List<SmallDescriptionOfWorkflowsReturnedByServerDuringListing> workflows) {
    this.workflows = workflows;
    return this;
  }

  public ReturnEnvelopeForWorkflowListing addWorkflowsItem(SmallDescriptionOfWorkflowsReturnedByServerDuringListing workflowsItem) {
    if (this.workflows == null) {
      this.workflows = new ArrayList<SmallDescriptionOfWorkflowsReturnedByServerDuringListing>();
    }
    this.workflows.add(workflowsItem);
    return this;
  }

   /**
   * Get workflows
   * @return workflows
  **/
  @ApiModelProperty(value = "")
  public List<SmallDescriptionOfWorkflowsReturnedByServerDuringListing> getWorkflows() {
    return workflows;
  }

  public void setWorkflows(List<SmallDescriptionOfWorkflowsReturnedByServerDuringListing> workflows) {
    this.workflows = workflows;
  }

  public ReturnEnvelopeForWorkflowListing nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * Get nextPageToken
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnEnvelopeForWorkflowListing returnEnvelopeForWorkflowListing = (ReturnEnvelopeForWorkflowListing) o;
    return Objects.equals(this.workflows, returnEnvelopeForWorkflowListing.workflows) &&
        Objects.equals(this.nextPageToken, returnEnvelopeForWorkflowListing.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflows, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnEnvelopeForWorkflowListing {\n");
    
    sb.append("    workflows: ").append(toIndentedString(workflows)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

