/*
 * task_execution.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nextflow.ga4gh.tes.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets tesFileType
 */
@JsonAdapter(TesFileType.Adapter.class)
public enum TesFileType {
  
  FILE("FILE"),
  
  DIRECTORY("DIRECTORY");

  private String value;

  TesFileType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TesFileType fromValue(String text) {
    for (TesFileType b : TesFileType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TesFileType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TesFileType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TesFileType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TesFileType.fromValue(String.valueOf(value));
    }
  }
}

