/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.agent

import java.util.regex.Pattern

import groovy.transform.CompileStatic

/**
 * The agent task script as it may be recorded, as opposed to as it must be executed.
 *
 * <p>A canonical agent task's script is the proxy launch command built by
 * {@code AgentDef.createCanonicalBody}, and it carries the invocation's capability token on argv:
 * {@code exec <proxy> --endpoint ... --token <TOKEN>}. That token is a BEARER CREDENTIAL. It
 * authorizes one connection to the driver's RPC broker, and since the driver answers a
 * {@code connect} with the start frame -- which now carries the provider API key resolved for the
 * agent -- whoever holds a live token can obtain that key.
 *
 * <p>The work directory is the accepted blast radius for it: the same text lands in
 * {@code .command.sh}, which is a residual documented in {@code docs/agent.mdx}. What is NOT
 * accepted is the token leaving that directory. {@link nextflow.trace.TraceRecord#script} is
 * persisted in the resume cache database and POSTed to Seqera Platform by {@code nf-tower}, so a
 * verbatim script there turns a work-dir-local secret into one that is stored and transmitted
 * off-box, for the life of the cache rather than for the capability's window.
 *
 * <p>{@code LinObserver.newAgentRun} already omits {@code task.script} from the lineage record for
 * exactly this reason; this is the same decision applied to the trace record, which cannot simply
 * omit the field.
 *
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
@CompileStatic
class AgentTaskScript {

    /** Stands in for the capability token wherever the script is recorded rather than executed. */
    static final String REDACTED = '[REDACTED]'

    /**
     * The launch command quotes every argument ({@code AgentLaunchSpec.shellCommand}), so this is the shape
     * the driver actually produces. The token is generated by the broker from
     * {@link java.security.SecureRandom} and rendered URL-safe, so it never contains a quote.
     */
    private static final Pattern QUOTED_TOKEN = ~/('--token'[ \t]+)'[^']*'/

    /**
     * The unquoted spellings, matched as a backstop so a future call site that composes the command
     * differently cannot silently reintroduce the leak.
     */
    private static final Pattern PLAIN_TOKEN = ~/(--token[=\s]+)\S+/

    private AgentTaskScript() {}

    /**
     * Whether the given task config belongs to an agent task. Guarded with {@code instanceof}, like
     * {@code LinObserver}, so a user-supplied {@code agentInfo} directive is inert rather than a way
     * to influence what gets recorded.
     *
     * @param config the task config, i.e. {@code TaskRun.config}
     */
    static boolean isAgentTask(Map config) {
        return config != null && config.get(AgentTaskInfo.CONFIG_KEY) instanceof AgentTaskInfo
    }

    /**
     * The given script with the RPC capability token replaced by {@link #REDACTED}. Everything else
     * -- the proxy path, the endpoint, the invocation id, the certificate fingerprint -- is kept:
     * none is a secret (a fingerprint is a public commitment) and all of it is what makes a
     * recorded script worth having.
     *
     * <p>Returns the input unchanged when there is no token to redact, so a non-RPC agent script is
     * untouched rather than reformatted.
     */
    static String redactCapabilityToken(String script) {
        if( !script || !script.contains('--token') )
            return script
        String result = QUOTED_TOKEN.matcher(script).replaceAll("\$1'${REDACTED}'")
        return PLAIN_TOKEN.matcher(result).replaceAll("\$1${REDACTED}")
    }

    /**
     * The recordable form of a task script: redacted for an agent task, byte-identical for every
     * other task. The identity branch is the contract -- this sits on the path taken by EVERY task
     * ({@code TaskRun.getTraceScript}), so an ordinary process must be able to prove it is untouched.
     */
    static String forTrace(Map config, String script) {
        return isAgentTask(config) ? redactCapabilityToken(script) : script
    }
}
