/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.config.parser.v2;

import nextflow.config.ConfigClosurePlaceholder;
import org.codehaus.groovy.ast.ClassCodeVisitorSupport;
import org.codehaus.groovy.ast.ClassNode;
import org.codehaus.groovy.ast.expr.ArgumentListExpression;
import org.codehaus.groovy.ast.expr.ClosureExpression;
import org.codehaus.groovy.ast.expr.ConstructorCallExpression;
import org.codehaus.groovy.ast.expr.Expression;
import org.codehaus.groovy.ast.expr.ListExpression;
import org.codehaus.groovy.ast.expr.MapExpression;
import org.codehaus.groovy.ast.expr.MethodCallExpression;
import org.codehaus.groovy.control.SourceUnit;

import static org.codehaus.groovy.ast.tools.GeneralUtils.*;
/**
 * AST transformation to render closure source text
 *
 * @author Ben Sherman <bentshermann@gmail.com>
 */
class ClosureToStringVisitor extends ClassCodeVisitorSupport {

    private static final String DIRECTIVE_REFS_CLOSURE = "nextflow.script.DirectiveRefsClosure";

    protected SourceUnit sourceUnit;

    public ClosureToStringVisitor(SourceUnit sourceUnit) {
        this.sourceUnit = sourceUnit;
    }

    @Override
    protected SourceUnit getSourceUnit() {
        return sourceUnit;
    }

    @Override
    public void visitMethodCallExpression(MethodCallExpression node) {
        var name = node.getMethodAsString();
        if( !"assign".equals(name) ) {
            super.visitMethodCallExpression(node);
            return;
        }

        var arguments = (ArgumentListExpression) node.getArguments();
        if( arguments.getExpressions().size() != 2 )
            return;

        var secondArg = arguments.getExpression(1);
        var replaced = replaceClosures(secondArg);
        if( replaced != secondArg )
            node.setArguments(args(arguments.getExpression(0), replaced));
    }

    /**
     * Recursively replace any closure expression -- whether it is the
     * value being assigned directly, or nested inside a list and/or map
     * literal at any depth (e.g. {@code publishDir = [[path: {...}], ...]})
     * -- with a placeholder that preserves its source text.
     */
    protected Expression replaceClosures(Expression node) {
        if( node instanceof ClosureExpression ce ) {
            return wrapExprAsPlaceholder(ce);
        }
        // A directive value referencing a `task` directive has been wrapped into a
        // `DirectiveRefsClosure` constructor call by ConfigToGroovyVisitor, which runs
        // before this visitor. Unwrap it to reach the closure it holds, otherwise the value
        // is left as a constructor call and rendered as an object identity -- which would
        // corrupt the output of `nextflow config` and the config generated by `kuberun`.
        // The wrapper is dropped, not preserved: this rendering path only produces config
        // text, so the collected names are of no use to it
        if( node instanceof ConstructorCallExpression cce
                && DIRECTIVE_REFS_CLOSURE.equals(cce.getType().getName())
                && cce.getArguments() instanceof ArgumentListExpression ale
                && ale.getExpressions().size() > 0 ) {
            return replaceClosures(ale.getExpression(0));
        }
        if( node instanceof ListExpression le ) {
            var items = le.getExpressions();
            for( int i = 0; i < items.size(); i++ )
                items.set(i, replaceClosures(items.get(i)));
            return le;
        }
        if( node instanceof MapExpression me ) {
            for( var entry : me.getMapEntryExpressions() )
                entry.setValueExpression(replaceClosures(entry.getValueExpression()));
            return me;
        }
        return node;
    }

    protected Expression wrapExprAsPlaceholder(Expression node) {
        var type = new ClassNode(ConfigClosurePlaceholder.class);
        var text = constX(getSourceText(node));
        return ctorX(type, args(text));
    }

    protected String getSourceText(Expression node) {
        var builder = new StringBuilder();
        var colBegin = Math.max(node.getColumnNumber()-1, 0);
        var colEnd = Math.max(node.getLastColumnNumber()-1, 0);
        var lineFirst = node.getLineNumber();
        var lineLast = node.getLastLineNumber();

        for( int i = lineFirst; i <= lineLast; i++ ) {
            var line = sourceUnit.getSource().getLine(i, null);
            if( i == lineFirst ) {
                var str = i == lineLast ? line.substring(colBegin,colEnd) : line.substring(colBegin);
                builder.append(str);
            }
            else {
                var str = i == lineLast ? line.substring(0, colEnd) : line;
                builder.append('\n');
                builder.append(str);
            }
        }
        return builder.toString();
    }

}
