flowchart TD
    p0((Channel.fromPath))
    p1([ifEmpty])
    p2[get_shuffle_replicates]
    p3[get_msa_replicates]
    p4[get_msa_trees]
    p5([collectFile])
    p6([first])
    p7[get_stable_msa_trees]
    p8(( ))
    p9[get_seqboot_replicates]
    p10[get_replicate_trees]
    p11([collectFile])
    p12([max])
    p13[get_shootstrap_tree]
    p14(( ))
    p0 --> p1
    p1 -->|file_names| p2
    p2 -->|shuffle_replicates| p3
    p3 -->|msa_replicates| p4
    p3 -->|msa_replicates2| p9
    p4 -->|msa_trees| p7
    p4 -->|msa_trees2| p5
    p5 --> p6
    p6 --> p7
    p7 -->|stable_trees| p8
    p7 -->|most_stable_tree| p12
    p9 -->|replicates| p10
    p10 -->|trees| p11
    p11 --> p13
    p12 --> p13
    p13 -->|shootstrap_tree| p14