/*
 * Copyright 2013-2026, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package nextflow.agent

import groovy.json.JsonOutput
import spock.lang.Specification

/**
 * <b>This is a tripwire, not a unit test.</b>
 *
 * <p>The six {@code fs:} descriptors are the CONTRACT the model is shown for the in-JVM filesystem
 * tools: the tool name it must call, the prose telling it when to, and the {@code parameters} schema
 * that decides which arguments it is allowed to send. {@link FilesystemToolsTest} and
 * {@link ModuleToolBridgeFilesystemTest} assert which NAMES are advertised; nothing asserted the
 * bytes, so every description and every property schema below could be rewritten by a refactor with
 * the whole suite still green.
 *
 * <p><b>This is deliberately NOT a cache-key pin, and that is the reason it has to exist.</b>
 * {@code AgentDef.toolsFingerprint} folds runner-native tools in as
 * {@code ['runner-native', runnerId, <sorted names>]} — the NAMES and the runner identity, never
 * these descriptors. So a reworded description or a dropped {@code required} entry moves no task
 * hash, breaks no {@code -resume}, and fails no other test: the only symptom is a model that is told
 * something different about its tools and starts calling them differently. That is precisely the
 * class of change nothing else in the suite can see.
 *
 * <p>The expected values were obtained by RUNNING {@link FilesystemTools#descriptors}, not by
 * reasoning about what it ought to produce, and are asserted with {@code ==} against whole literals
 * rather than {@code contains}. The input schemas are pinned as {@code JsonOutput.toJson} —
 * insertion order, which is what the model is shown — so a reordered property is a failure too.
 *
 * <p><b>Do not "fix" a failure here by updating an expected value.</b> A failure means the tool
 * contract moved. Either revert the change, or — if the rewording is intentional — update the
 * literal deliberately, knowing that every agent relying on the old prose now sees the new.
 *
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
class FilesystemToolDescriptorPinTest extends Specification {

    // --- the pinned bytes, generated by running FilesystemTools.descriptors(NAMES) -------------

    private static final String READ_DESC = 'Read the contents of a single file. Small text-like files (.txt .md .json .yaml .yml .csv .tsv .tab .log) are returned inline under `content`; every other file — binary, bulk data, or over the inline size limit — is returned as an opaque absolute `path` handle you can pass to another tool but cannot see the bytes of. Use `ls` first if you are unsure the file exists. Confined to the agent sandbox: the task work dir plus any module-output files returned by an earlier tool call. A path outside it is refused.'

    private static final String READ_SCHEMA = '{"type":"object","properties":{"path":{"type":"string","description":"File to read, relative to the agent work dir (or an absolute path inside the sandbox)."}},"required":["path"],"additionalProperties":false}'

    private static final String WRITE_DESC = 'Create a file or replace its entire contents. Missing parent directories are created. To change part of an existing file use `edit` instead — this tool overwrites everything. Writes are confined to the agent work dir only: unlike reads, a module-output path outside the work dir is NOT writable.'

    private static final String WRITE_SCHEMA = '{"type":"object","properties":{"path":{"type":"string","description":"File to write, relative to the agent work dir. Missing parent directories are created."},"content":{"type":"string","description":"The full new contents of the file. The file is overwritten, not appended to."}},"required":["path","content"],"additionalProperties":false}'

    private static final String EDIT_DESC = 'Replace an exact literal string in an existing file, leaving the rest untouched. `old_string` is matched literally, never as a regular expression. If it occurs more than once the edit is REFUSED rather than applied to the first match: either extend `old_string` with surrounding lines until it is unique, or pass `replace_all: true` when you really mean every occurrence. The number of replacements made is reported back. Edits are confined to the agent work dir only, like writes.'

    private static final String EDIT_SCHEMA = '{"type":"object","properties":{"path":{"type":"string","description":"File to edit, relative to the agent work dir."},"old_string":{"type":"string","description":"The exact text to replace, including whitespace and indentation. Must occur exactly once in the file unless `replace_all` is true."},"new_string":{"type":"string","description":"The text to put in its place. May be empty to delete the matched text."},"replace_all":{"type":"boolean","description":"Replace every occurrence instead of requiring a unique one. Defaults to false."}},"required":["path","old_string","new_string"],"additionalProperties":false}'

    private static final String LS_DESC = 'List the immediate entries of a directory (not recursive). Each entry reports its `name`, its `type` (`file` or `dir`) and, for a file, its `size` in bytes — so you can tell whether reading it is worthwhile. Use `find` to search a directory tree instead. Confined to the agent sandbox: the task work dir plus any module-output files returned by an earlier tool call. A path outside it is refused.'

    private static final String LS_SCHEMA = '{"type":"object","properties":{"path":{"type":"string","description":"Directory to list, relative to the agent work dir. Defaults to the work dir itself."}},"required":[],"additionalProperties":false}'

    private static final String GREP_DESC = 'Search file contents line by line for a regular expression, recursively. Returns one entry per matching line with its absolute `file`, 1-based `line` number and the matched line `text` (truncated to 300 characters). Binary files and files larger than 2 MB are skipped. When more lines match than the limit allows the result sets `truncated: true` with `truncated_reason: "max_results"` and reports the `limit` used — narrow the pattern or the `include` glob rather than assuming you saw everything. The search itself is also bounded (at most 20000 entries visited and 2000 files read): when THAT stops it, `truncated_reason` is `"search_budget"` and the tree was NOT searched to the end — narrow the search root or the depth. Confined to the agent sandbox: the task work dir plus any module-output files returned by an earlier tool call. A path outside it is refused.'

    private static final String GREP_SCHEMA = '{"type":"object","properties":{"pattern":{"type":"string","description":"Regular expression (Java/PCRE syntax) matched against each line. A plain substring is a valid pattern."},"path":{"type":"string","description":"File or directory to search, relative to the agent work dir. Defaults to the work dir itself."},"include":{"type":"string","description":"Optional glob restricting which files are searched, e.g. `*.tsv`. Matched against the file name, or against the path relative to the search root when it contains a `/`."},"case_insensitive":{"type":"boolean","description":"Match case-insensitively. Defaults to false."},"max_results":{"type":"integer","description":"Maximum number of matching lines to return. Defaults to 200, capped at 1000."},"max_depth":{"type":"integer","description":"Maximum directory depth to descend. Defaults to 20, capped at 50."}},"required":["pattern"],"additionalProperties":false}'

    private static final String FIND_DESC = 'Find files and directories by name, recursively, returning their absolute paths. This searches NAMES only — use `grep` to search file contents. When more paths match than the limit allows the result sets `truncated: true` with `truncated_reason: "max_results"` and reports the `limit` used. The search itself is also bounded (at most 20000 entries visited): when THAT stops it, `truncated_reason` is `"search_budget"` and the tree was NOT searched to the end — narrow the search root or the depth. Confined to the agent sandbox: the task work dir plus any module-output files returned by an earlier tool call. A path outside it is refused.'

    private static final String FIND_SCHEMA = '{"type":"object","properties":{"pattern":{"type":"string","description":"Glob matched against the file NAME, e.g. `*.fastq.gz`. A pattern containing a `/` is matched against the path relative to the search root instead, e.g. `**/results/*.json`."},"path":{"type":"string","description":"Directory to search, relative to the agent work dir. Defaults to the work dir itself."},"type":{"type":"string","enum":["file","dir","any"],"description":"Restrict results to regular files or to directories. Defaults to `any`."},"max_results":{"type":"integer","description":"Maximum number of paths to return. Defaults to 200, capped at 1000."},"max_depth":{"type":"integer","description":"Maximum directory depth to descend. Defaults to 20, capped at 50."}},"required":["pattern"],"additionalProperties":false}'

    // --- the pins ----------------------------------------------------------------------------

    def 'should advertise exactly the six fs tools, in this order'() {
        expect:
        FilesystemTools.NAMES == ['read', 'write', 'edit', 'ls', 'grep', 'find']
    }

    def 'should pin the descriptor bytes of every fs tool'() {
        given:
        final byName = FilesystemTools.descriptors(FilesystemTools.NAMES).collectEntries { [it.name, it] }

        expect:
        byName[name].description == description
        JsonOutput.toJson(byName[name].inputSchema) == schema
        // no fs: tool declares an output schema -- the shape is described in prose, in the
        // description above, because these results are handed straight to the model as JSON
        byName[name].outputSchema == null

        where:
        name    | description  | schema
        'read'  | READ_DESC    | READ_SCHEMA
        'write' | WRITE_DESC   | WRITE_SCHEMA
        'edit'  | EDIT_DESC    | EDIT_SCHEMA
        'ls'    | LS_DESC      | LS_SCHEMA
        'grep'  | GREP_DESC    | GREP_SCHEMA
        'find'  | FIND_DESC    | FIND_SCHEMA
    }

    def 'should return the selected leaves only, in the order given'() {
        expect:
        FilesystemTools.descriptors(['grep', 'read'])*.name == ['grep', 'read']
        FilesystemTools.descriptors([]).isEmpty()
    }
}
