name: Security SCA scan for branch
description: Scan nextflow branch for security vulnerabilities on third-party dependencies

inputs: 
  branch:
    description: The branch to scan for security vulnerabilities
    required: true

runs: 
  using: "composite"
  steps:
    - name: Checkout repository first
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Checkout target branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
        path: target-branch


    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version || '21' }}
        distribution: 'temurin'
        architecture: x64
        cache: gradle

    - name: Compile
      shell: bash
      run: cd target-branch && make assemble

    - name: assume role
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df #v4.2.1
      with:
        aws-region: "eu-west-1"
        role-to-assume: "arn:aws:iam::730335503331:role/AmazonInspectorScanRoleForNextflow" 

    - name: Run SCA scan
      id: inspector
      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@5dc8a4bafed85c4c3d7070b4a7ada5b9d94041e3 #v1.2.1
      with:
        artifact_type: "repository"
        artifact_path: './target-branch'
        display_vulnerability_findings: "enabled"
        critical_threshold: 1
        high_threshold: 1

    - name: Upload Scan Results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: Inspector Vulnerability Scan Artifacts
        path: |
          ${{ steps.inspector.outputs.inspector_scan_results }}
          ${{ steps.inspector.outputs.inspector_scan_results_csv }}
          ${{ steps.inspector.outputs.artifact_sbom }}
          ${{ steps.inspector.outputs.inspector_scan_results_markdown }}

    - name: On vulnerability threshold exceeded
      run: exit ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}
      shell: bash



