name: Docs CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'docs/**'
  workflow_dispatch:
jobs:
  docs-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.9.25'

      - name: Test docs build
        run: |
          cd docs/
          pip install -r requirements.txt
          make clean html
