name: Docs CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'docs/**'
  workflow_dispatch:
jobs:
  docs-build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build
