name: Generate and submit dependency graph for nextflow
on:
    push:
      branches: ['master']

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        components: ["nextflow", "plugins:nf-google", "plugins:nf-amazon", "plugins:nf-azure", "plugins:nf-cloudcache", "plugins:nf-codecommit", "plugins:nf-console", "plugins:nf-tower", "plugins:nf-wave"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Generate and submit dependency graph for nextflow
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-resolution-task: ":${{ matrix.components }}:dependencies"
        additional-arguments: "--configuration runtimeClasspath"
        dependency-graph: generate-and-submit
