name: Release

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  # --------------------------------------------------
  # job: release
  # --------------------------------------------------
  release:
    name: Assemble
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # --------------------------
      # setup
      # --------------------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to Seqera registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.SEQERA_PUBLIC_CR_URL }}
          username: ${{ secrets.SEQERA_PUBLIC_CR_USER }}
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}

      # --------------------------
      # assemble
      # --------------------------
      - name: Compile
        run: make distribution

      # --------------------------
      # upload artifacts
      # --------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: distribution
          path: |
            modules/*/build/libs/
            build/releases/

      - name: Upload artifacts (plugins)
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: plugins
          path: |
            plugins/build/libs/
            plugins/*/build/libs/

      # --------------------------
      # tag
      # --------------------------
      - name: Tag
        run: bash .github/scripts/tag-release.sh

      # --------------------------
      # deploy-maven
      # --------------------------
      - name: Deploy to maven
        run: bash .github/scripts/deploy-to-maven.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          MAVEN_PUBLISH_URL: ${{ vars.MAVEN_PUBLISH_URL }}

      # --------------------------
      # deploy-s3
      # --------------------------
      - name: Deploy to S3
        run: bash .github/scripts/deploy-to-s3.sh
        env:
          S3_RELEASE_BUCKET: ${{ vars.S3_RELEASE_BUCKET }}

      # --------------------------
      # deploy-docker
      # --------------------------
      - name: Deploy to docker
        run: bash .github/scripts/deploy-to-docker.sh
        env:
          SEQERA_REGISTRY: ${{ vars.SEQERA_PUBLIC_CR_URL }}

      # --------------------------
      # deploy-github
      # --------------------------
      - name: Create github release
        run: bash .github/scripts/deploy-to-github.sh
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

      # --------------------------
      # deploy-plugins
      # --------------------------
      - name: Deploy plugins to maven
        run: bash .github/scripts/deploy-plugins-to-maven.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          MAVEN_PUBLISH_URL: ${{ vars.MAVEN_PLUGINS_PUBLISH_URL }}

      - name: Deploy plugins to github
        run: bash .github/scripts/deploy-plugins-to-github.sh
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          GH_ORG: ${{ vars.PLUGINS_GITHUB_ORG }}

      - name: Update plugins index
        run: bash .github/scripts/update-plugins-index.sh
        env:
          GH_ORG: ${{ vars.PLUGINS_GITHUB_ORG }}
          GH_USER: ${{ vars.DEPLOY_GITHUB_USER }}
          GH_USER_EMAIL: ${{ vars.DEPLOY_GITHUB_EMAIL }}
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          PLUGINS_INDEX_JSON: ${{ vars.PLUGINS_INDEX_JSON }}

      # --------------------------
      # publish
      # --------------------------
      - name: Publish release
        run: bash .github/scripts/publish-release.sh
        env:
          S3_RELEASE_BUCKET: ${{ vars.S3_RELEASE_BUCKET }}
