name: Security SCA Scan Cron weekly
# This workflow runs a security scan on master push

on:
  push:
    branches:
      - master
jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Run Security SCA Scan
        uses: ./.github/actions/security-scan-branch
