name: Security SCA Scan

on:
    pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Run Security SCA Scan
        uses: ./.github/actions/security-scan-branch
        with:
          branch: "v25.04.2"
